title: Kando
description: The cross-platform pie menu.
theme: just-the-docs

url: https://kando.menu
baseurl: /documentation

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
